services:
  catalog_api_mongodb:
    container_name: mongodb
    image: mongo:6.0.13-jammy
    environment:
      MONGO_INITDB_ROOT_USERNAME: viepovsky
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: catalog
    volumes:
      - mongo_volume:/var/lib/mongo
    ports:
      - 27017:27017
    networks:
      - mongo_network
    restart: unless-stopped

  mongo-express:
    container_name: mongo-express
    image: mongo-express:1.0.0-18
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=viepovsky
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    volumes:
      - mongo_volume:/var/lib/express
    ports:
      - 8000:8081
    networks:
      - mongo_network
    depends_on:
      - catalog_api_mongodb
    restart: unless-stopped

networks:
  mongo_network:
    driver: bridge

volumes:
  mongo_volume: